// This file is auto-generated by @hey-api/openapi-ts

export const Barchart_risk_bands_DataSchema = {
    properties: {
        one_0_2: {
            type: 'integer',
            title: 'One 0 2'
        },
        two_0_4: {
            type: 'integer',
            title: 'Two 0 4'
        },
        three_0_6: {
            type: 'integer',
            title: 'Three 0 6'
        },
        four_0_8: {
            type: 'integer',
            title: 'Four 0 8'
        },
        five_1: {
            type: 'integer',
            title: 'Five 1'
        }
    },
    type: 'object',
    required: ['one_0_2', 'two_0_4', 'three_0_6', 'four_0_8', 'five_1'],
    title: 'Barchart_risk_bands_Data'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_transactions_Add_TxSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_transactions-Add_Tx'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HeatMap_DataSchema = {
    properties: {
        Column_POS: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Column Pos'
        },
        POS_fraud: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Pos Fraud'
        },
        Column_Online: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Column Online'
        },
        Online_fraud: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Online Fraud'
        },
        Column_ATM_Withdrawal: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Column Atm Withdrawal'
        },
        ATM_Withdrawal_fraud: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Atm Withdrawal Fraud'
        },
        Column_Bank_Transfer: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Column Bank Transfer'
        },
        Bank_Transfer_fraud: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Bank Transfer Fraud'
        }
    },
    type: 'object',
    required: ['Column_POS', 'POS_fraud', 'Column_Online', 'Online_fraud', 'Column_ATM_Withdrawal', 'ATM_Withdrawal_fraud', 'Column_Bank_Transfer', 'Bank_Transfer_fraud'],
    title: 'HeatMap_Data'
} as const;

export const KPISummarySchema = {
    properties: {
        total_transactions: {
            type: 'integer',
            title: 'Total Transactions'
        },
        total_exposure_amount: {
            type: 'number',
            title: 'Total Exposure Amount'
        },
        total_fraud_count: {
            type: 'integer',
            title: 'Total Fraud Count'
        },
        total_fraud_value: {
            type: 'number',
            title: 'Total Fraud Value'
        },
        avg_top_decile_risk: {
            type: 'number',
            title: 'Avg Top Decile Risk'
        }
    },
    type: 'object',
    required: ['total_transactions', 'total_exposure_amount', 'total_fraud_count', 'total_fraud_value', 'avg_top_decile_risk'],
    title: 'KPISummary'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RadialPolarBarSchema = {
    properties: {
        Hours: {
            items: {
                type: 'number'
            },
            type: 'array',
            title: 'Hours'
        }
    },
    type: 'object',
    required: ['Hours'],
    title: 'RadialPolarBar'
} as const;

export const Sankey_DataSchema = {
    properties: {
        Transaction_count: {
            type: 'integer',
            title: 'Transaction Count'
        },
        Transaction_Type_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 4,
            minItems: 4,
            title: 'Transaction Type Values'
        },
        Ttype_DeType_Laptop_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 4,
            minItems: 4,
            title: 'Ttype Detype Laptop Values'
        },
        Ttype_DeType_Tablet_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 4,
            minItems: 4,
            title: 'Ttype Detype Tablet Values'
        },
        Ttype_DeType_Mobile_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 4,
            minItems: 4,
            title: 'Ttype Detype Mobile Values'
        },
        DeType_High_Risk_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Detype High Risk Values'
        },
        DeType_Medium_Risk_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Detype Medium Risk Values'
        },
        DeType_Low_Risk_Values: {
            prefixItems: [
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'integer'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Detype Low Risk Values'
        }
    },
    type: 'object',
    required: ['Transaction_count', 'Transaction_Type_Values', 'Ttype_DeType_Laptop_Values', 'Ttype_DeType_Tablet_Values', 'Ttype_DeType_Mobile_Values', 'DeType_High_Risk_Values', 'DeType_Medium_Risk_Values', 'DeType_Low_Risk_Values'],
    title: 'Sankey_Data'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TransactionSchema = {
    properties: {
        Transaction_ID: {
            type: 'string',
            title: 'Transaction Id'
        },
        User_ID: {
            type: 'string',
            title: 'User Id'
        },
        Transaction_Amount: {
            type: 'number',
            title: 'Transaction Amount'
        },
        Account_Balance: {
            type: 'number',
            title: 'Account Balance'
        },
        Avg_Transaction_Amount_7d: {
            type: 'number',
            title: 'Avg Transaction Amount 7D'
        },
        Transaction_Distance: {
            type: 'number',
            title: 'Transaction Distance'
        },
        Risk_Score: {
            type: 'number',
            title: 'Risk Score'
        },
        Transaction_Type: {
            type: 'string',
            title: 'Transaction Type'
        },
        Device_Type: {
            type: 'string',
            title: 'Device Type'
        },
        Location: {
            type: 'string',
            title: 'Location'
        },
        Merchant_Category: {
            type: 'string',
            title: 'Merchant Category'
        },
        Card_Type: {
            type: 'string',
            title: 'Card Type'
        },
        Authentication_Method: {
            type: 'string',
            title: 'Authentication Method'
        },
        Timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        },
        IP_Address_Flag: {
            type: 'integer',
            title: 'Ip Address Flag'
        },
        Previous_Fraudulent_Activity: {
            type: 'integer',
            title: 'Previous Fraudulent Activity'
        },
        Is_Weekend: {
            type: 'integer',
            title: 'Is Weekend'
        },
        Fraud_Label: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fraud Label'
        },
        Fraud_Probability: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fraud Probability'
        },
        Daily_Transaction_Count: {
            type: 'integer',
            title: 'Daily Transaction Count'
        },
        Failed_Transaction_Count_7d: {
            type: 'integer',
            title: 'Failed Transaction Count 7D'
        },
        Card_Age: {
            type: 'integer',
            title: 'Card Age'
        }
    },
    type: 'object',
    required: ['Transaction_ID', 'User_ID', 'Transaction_Amount', 'Account_Balance', 'Avg_Transaction_Amount_7d', 'Transaction_Distance', 'Risk_Score', 'Transaction_Type', 'Device_Type', 'Location', 'Merchant_Category', 'Card_Type', 'Authentication_Method', 'Timestamp', 'IP_Address_Flag', 'Previous_Fraudulent_Activity', 'Is_Weekend', 'Daily_Transaction_Count', 'Failed_Transaction_Count_7d', 'Card_Age'],
    title: 'Transaction'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VisualsSchema = {
    properties: {
        RadialPolar: {
            '$ref': '#/components/schemas/RadialPolarBar'
        },
        HeatMap: {
            '$ref': '#/components/schemas/HeatMap_Data'
        },
        Barchart: {
            '$ref': '#/components/schemas/Barchart_risk_bands_Data'
        },
        Sankey: {
            '$ref': '#/components/schemas/Sankey_Data'
        }
    },
    type: 'object',
    required: ['RadialPolar', 'HeatMap', 'Barchart', 'Sankey'],
    title: 'Visuals'
} as const;