// This file is auto-generated by @hey-api/openapi-ts

export type Barchart_risk_bands_Data = {
    bands: Array<(number)>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_transactions_Add_Tx = {
    file: (Blob | File);
};

export type HeatMap_Data = {
    heat: Array<Array<(number)>>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KPISummary = {
    total_transactions: number;
    total_exposure_amount: number;
    total_fraud_count: number;
    total_fraud_value: number;
    avg_top_decile_risk: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RadialPolarBar = {
    Hours: Array<(number)>;
};

export type Sankey_Data = {
    Links: Array<Sankey_Link>;
};

export type Sankey_Link = {
    From: string;
    To: string;
    Value: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type Transaction = {
    Transaction_ID: string;
    User_ID: string;
    Transaction_Amount: number;
    Account_Balance: number;
    Avg_Transaction_Amount_7d: number;
    Transaction_Distance: number;
    Risk_Score: number;
    Transaction_Type: string;
    Device_Type: string;
    Location: string;
    Merchant_Category: string;
    Card_Type: string;
    Authentication_Method: string;
    Timestamp: string;
    IP_Address_Flag: number;
    Previous_Fraudulent_Activity: number;
    Is_Weekend: number;
    Fraud_Label?: (number | null);
    Fraud_Probability?: (number | null);
    Daily_Transaction_Count: number;
    Failed_Transaction_Count_7d: number;
    Card_Age: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Visuals = {
    RadialPolar: RadialPolarBar;
    HeatMap: HeatMap_Data;
    Barchart: Barchart_risk_bands_Data;
    Sankey: Sankey_Data;
};

export type KpisReadKpisResponse = (KPISummary);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TransactionsAddTxData = {
    formData: Body_transactions_Add_Tx;
};

export type TransactionsAddTxResponse = (Array<Transaction>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type VisualsReadKpisResponse = (Visuals);