"""tx table

Revision ID: dd703fee3600
Revises: fe56fa70289e
Create Date: 2026-04-29 00:48:49.295639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd703fee3600'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transaction',
    sa.Column('Transaction_ID', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('User_ID', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Transaction_Amount', sa.Float(), nullable=False),
    sa.Column('Account_Balance', sa.Float(), nullable=False),
    sa.Column('Avg_Transaction_Amount_7d', sa.Float(), nullable=False),
    sa.Column('Transaction_Distance', sa.Float(), nullable=False),
    sa.Column('Risk_Score', sa.Float(), nullable=False),
    sa.Column('Transaction_Type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Device_Type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Merchant_Category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Card_Type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Authentication_Method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('IP_Address_Flag', sa.Integer(), nullable=False),
    sa.Column('Previous_Fraudulent_Activity', sa.Integer(), nullable=False),
    sa.Column('Is_Weekend', sa.Integer(), nullable=False),
    sa.Column('Fraud_Label', sa.Integer(), nullable=True),
    sa.Column('Daily_Transaction_Count', sa.Integer(), nullable=False),
    sa.Column('Failed_Transaction_Count_7d', sa.Integer(), nullable=False),
    sa.Column('Card_Age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Transaction_ID')
    )
    op.create_index(op.f('ix_transaction_User_ID'), 'Transaction', ['User_ID'], unique=False)
    # ### end Alembic commands ###



def downgrade():
    pass
